working_directory = "./Developer"

[font]
normal.family = "FiraCode Nerd Font"
normal.style = "Retina"
size = 16 

[window]
dimensions.columns = 100
dimensions.lines = 30
dynamic_title = true
option_as_alt = "Both"
padding.y = 10

[cursor]
style.blinking = "Never"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

